const { MessageEmbed } = require('discord.js');
const fs = require('fs');
const config = require('../../config.json');

const generated = new Set();

module.exports = {
  name: 'bgen',
  description: 'Generate a specified service if stocked (basic)',
  usage: 'bgen <service>',

  execute(message, args) {
    try {
      // Check if the basichannelid is valid
      if (!message.client.channels.cache.has(config.basichannelid)) {
        throw new Error('Invalid basichannel specified');
      }
    } catch (error) {
      console.error(error);

      if (config.command.error_message) {
        return message.channel.send(
          new MessageEmbed()
            .setColor(config.color.red)
            .setTitle('Error occurred!')
            .setDescription('Not a valid basichannel specified!')
            .setFooter(message.author.tag, message.author.displayAvatarURL({ dynamic: true, size: 64 }))
            .setTimestamp()
        );
      } else {
        return;
      }
    }

    if (message.channel.id === config.basichannelid) {
      if (generated.has(message.author.id)) {
        return message.channel.send(
          new MessageEmbed()
            .setColor(config.color.red)
            .setTitle('Cooldown!')
            .setDescription(`Please wait **${config.bgenCooldown / 60000}m** before executing that command again!`)
            .setFooter(message.author.tag, message.author.displayAvatarURL({ dynamic: true, size: 64 }))
            .setTimestamp()
        );
      } else {
        const service = args[0];

        if (!service) {
          return message.channel.send(
            new MessageEmbed()
              .setColor(config.color.red)
              .setTitle('Missing parameters!')
              .setDescription('You need to provide a service name!')
              .setFooter(message.author.tag, message.author.displayAvatarURL({ dynamic: true, size: 64 }))
              .setTimestamp()
          );
        }

        const filePath = `${__dirname}/../../basicstock/${service}.txt`;

        fs.readFile(filePath, (error, data) => {
          if (!error) {
            data = data.toString();

            const firstLine = data.split('\n')[0];
            const remainingData = data.split('\n').slice(1).join('\n');

            if (!firstLine) {
              return message.channel.send(
                new MessageEmbed()
                  .setColor(config.color.red)
                  .setTitle('Generator error!')
                  .setDescription(`The \`${service}\` service is empty or not found!`)
                  .setFooter(message.author.tag, message.author.displayAvatarURL({ dynamic: true, size: 64 }))
                  .setTimestamp()
              );
            }

            const generatedCode = firstLine.trim();

            const currentTime = new Date();
            const formattedTime = `${currentTime.getFullYear()}-${(currentTime.getMonth() + 1)
              .toString()
              .padStart(2, '0')}-${currentTime.getDate().toString().padStart(2, '0')} ${
              currentTime.getHours().toString().padStart(2, '0')
            }:${currentTime.getMinutes().toString().padStart(2, '0')}:${currentTime.getSeconds().toString().padStart(2, '0')}`;

            const redemptionEmbed = new MessageEmbed()
              .setColor(config.color.green)
              .setTitle('NEXUS G3N')
              .setDescription('**Follow these steps to redeem your code:**\nStep 1: Click on this [LINK](https://link-center.net/991963/blue-gen-verify) , complete some steps and register with your Discord nickname.\nStep 2: Go to the Ticket channel\nStep 3: Click on Redeem a code\nStep 4: Send this code to staff:')
              .addField('Code', `\`\`\`${generatedCode}\`\`\``)
              .setFooter(`Generated by BLUE G3N • ${formattedTime}`);

            // DM the user with the embed
            message.author.send({ embeds: [redemptionEmbed] }).catch((err) => {
              console.error(`Failed to send DM to ${message.author.tag}: ${err}`);
            });

            // Save the code to redeemcodes.txt with the service name
            const redeemFilePath = `${__dirname}/../../redeemcodes/redeemcodes.txt`;
            fs.appendFileSync(redeemFilePath, `${generatedCode} - ${service} in basic category\n`);

            // Update the service file
            fs.writeFile(filePath, remainingData, (error) => {
              if (error) {
                console.error(error);
              } else {
                message.channel.send(
                  new MessageEmbed()
                    .setColor(config.color.green)
                    .setTitle('Account generated successfully!')
                    .setDescription(`Check your DMs ${message.author}! If you do not receive the message, please unlock your DMs!`)
                    .setImage(config.gif) // Use the URL from config.json
                    .setFooter(message.author.tag, message.author.displayAvatarURL({ dynamic: true, size: 64 }))
                    .setTimestamp()
                );

                generated.add(message.author.id);

                setTimeout(() => {
                  generated.delete(message.author.id);
                }, config.bgenCooldown);
              }
            });
          } else {
            return message.channel.send(
              new MessageEmbed()
                .setColor(config.color.red)
                .setTitle('Generator error!')
                .setDescription(`Service \`${service}\` does not exist!`)
                .setFooter(message.author.tag, message.author.displayAvatarURL({ dynamic: true, size: 64 }))
                .setTimestamp()
            );
          }
        });
      }
    } else {
      message.channel.send(
        new MessageEmbed()
          .setColor(config.color.red)
          .setTitle('Wrong command usage!')
          .setDescription(`You cannot use the \`bgen\` command in this channel! Try it in <#${config.basichannelid}>!`)
          .setFooter(message.author.tag, message.author.displayAvatarURL({ dynamic: true, size: 64 }))
          .setTimestamp()
      );
    }
  },
};